language: objective-c
xcode_project: ShazamLite.xcodeproj # path to your xcodeproj folder
xcode_scheme: ShazamLiteTests
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone X


language: swift
osx_image: xcode10.2

branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
script:
  - set -o pipefail
  - xcodebuild -workspace ShazamLite.xcworkspace -scheme ShazamLite -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
